name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build the app
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to GitHub Pages
        working-directory: ./frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Paras Verma"
          git config user.email "parasverma373@gmail.com"
          npx gh-pages -d build -u "Paras Verma <parasverma373@gmail.com>"
